#!/usr/bin/env bash
set -Eeuo pipefail

########################################
# Globals
########################################
TEMPLATE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="/etc/server.env"
STATE_DIR="/var/lib/server-template"
CERT_DIR="/etc/ssl/cf-origin"

log() { echo "[bootstrap] $*"; }
die() { echo "[bootstrap] ERROR: $*" >&2; exit 1; }

########################################
# Safety
########################################
[[ $EUID -eq 0 ]] || die "Must run as root"

########################################
# Helpers
########################################
ensure_dir() {
  install -d -o root -g root -m "${2:-0755}" "$1"
}

gen_secret() {
  openssl rand -base64 48 | tr -d '\n='
}

env_set_if_missing() {
  local k="$1" v="$2"
  grep -qE "^${k}=" "${ENV_FILE}" 2>/dev/null || echo "${k}=${v}" >> "${ENV_FILE}"
}

########################################
# Base packages
########################################
install_base_packages() {
  apt-get update -y
  apt-get install -y \
    ca-certificates curl gnupg lsb-release \
    cron logrotate unattended-upgrades \
    mariadb-server redis-server \
    nftables msmtp
}

########################################
# SSH removal
########################################
disable_ssh() {
  log "Removing SSH"
  systemctl stop ssh sshd 2>/dev/null || true
  systemctl disable ssh sshd 2>/dev/null || true
  systemctl mask ssh sshd 2>/dev/null || true
  apt-get purge -y openssh-server openssh-sftp-server || true
  rm -rf /etc/ssh
}

########################################
# /etc/server.env
########################################
ensure_env_file() {
  ensure_dir "$(dirname "${ENV_FILE}")"

  if [[ ! -f "${ENV_FILE}" ]]; then
    umask 077
    cat > "${ENV_FILE}" <<EOF
# Server configuration (generated by bootstrap)
# root:root 0600
EOF
    chmod 600 "${ENV_FILE}"
  fi

  # Core
  env_set_if_missing TZ "UTC"
  env_set_if_missing WEB_ROOT "/var/www/wordpress"

  # Database
  env_set_if_missing DB_NAME "wp_$(openssl rand -hex 4)"
  env_set_if_missing DB_USER "wp_$(openssl rand -hex 4)"
  env_set_if_missing DB_PASSWORD "$(gen_secret)"

  # Redis
  env_set_if_missing REDIS_PASSWORD "$(gen_secret)"

  # WordPress (admin creds generated now, used later)
  env_set_if_missing WP_PRIMARY_DOMAIN "example.invalid"
  env_set_if_missing WP_ADMIN_USER "admin"
  env_set_if_missing WP_ADMIN_PASSWORD "$(gen_secret)"
  env_set_if_missing WP_ADMIN_EMAIL "root@localhost"
  env_set_if_missing WP_SUBDOMAIN_INSTALL "1"

  # Mail placeholders (filled later)
  env_set_if_missing MAILGUN_SMTP_HOST "smtp.mailgun.org"
  env_set_if_missing MAILGUN_SMTP_PORT "587"
  env_set_if_missing MAILGUN_SMTP_LOGIN ""
  env_set_if_missing MAILGUN_SMTP_PASSWORD ""
  env_set_if_missing MAIL_FROM "server@example.invalid"
  env_set_if_missing ALERT_EMAIL "root@localhost"
}

########################################
# DB setup
########################################
install_db() {
  systemctl enable --now mariadb

  # shellcheck disable=SC1091
  source "${ENV_FILE}"

  mysql <<SQL
DELETE FROM mysql.user WHERE User='';
DROP DATABASE IF EXISTS test;
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL
}

########################################
# Redis (local only)
########################################
install_redis() {
  install -o root -g root -m 0644 "${TEMPLATE_DIR}/redis/redis.conf" /etc/redis/redis.conf
  systemctl enable --now redis-server
}

########################################
# Cert directory
########################################
prepare_cert_dir() {
  ensure_dir "${CERT_DIR}" 0755
}

########################################
# Disable cloud-init permanently
########################################
disable_cloud_init() {
  log "Disabling cloud-init permanently"
  touch /etc/cloud/cloud-init.disabled
}

########################################
# Main
########################################
main() {
  ensure_dir "${STATE_DIR}" 0700

  install_base_packages
  disable_ssh
  ensure_env_file
  install_db
  install_redis
  prepare_cert_dir
  disable_cloud_init

  log "Bootstrap complete. Reboot recommended."
}

main "$@"
