#!/usr/bin/env bash
set -Eeuo pipefail

mkdir -p /var/lib/server-template/cloudflare
chmod 0700 /var/lib/server-template/cloudflare
chown root:root /var/lib/server-template/cloudflare

# Ensure base state directory exists
install -d -o root -g root -m 0700 /var/lib/server-template \
  || die "Cannot create /var/lib/server-template"

install -d -o root -g root -m 0700 "${STATE_DIR}" \
  || die "Cannot create state dir: ${STATE_DIR}"

# Write test
touch "${STATE_DIR}/.writetest" \
  || die "State dir not writable: ${STATE_DIR}"
rm -f "${STATE_DIR}/.writetest"

###############################################################################
# Cloudflare IP updater for nftables + nginx
#
# - Always fetches fresh IPv4 + IPv6 ranges
# - Always flushes + repopulates nftables sets
# - Regenerates nginx real_ip config
# - Fails HARD if sets end up empty
###############################################################################

LOCK_FILE="/var/lock/cloudflare-update.lock"
exec 9>"${LOCK_FILE}"
flock -n 9 || exit 0

###############################################################################
# Paths / config
###############################################################################

ENV_FILE="/etc/server.env"

STATE_DIR="/var/lib/server-template/cloudflare"
V4_FILE="${STATE_DIR}/ips-v4.txt"
V6_FILE="${STATE_DIR}/ips-v6.txt"

REALIP_CONF="/etc/nginx/conf.d/cloudflare-realip.conf"

CF_V4_URL="https://www.cloudflare.com/ips-v4"
CF_V6_URL="https://www.cloudflare.com/ips-v6"

###############################################################################
# Helpers
###############################################################################

log() {
  echo "[cloudflare-update] $*"
}

die() {
  echo "[cloudflare-update] FATAL: $*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

###############################################################################
# Preconditions
###############################################################################

require_cmd curl
require_cmd nft
require_cmd awk
require_cmd grep
require_cmd sed

# Load env if present (non-fatal)
if [[ -f "${ENV_FILE}" ]]; then
  # shellcheck disable=SC1091
  source "${ENV_FILE}"
fi

# Ensure state dir exists
install -d -o root -g root -m 0700 "${STATE_DIR}"

###############################################################################
# Fetch Cloudflare IP lists
###############################################################################

log "Fetching Cloudflare IPv4 ranges"
curl -fsSL "${CF_V4_URL}" -o "${V4_FILE}"
[[ -s "${V4_FILE}" ]] || die "IPv4 list download failed or empty"

log "Fetching Cloudflare IPv6 ranges"
curl -fsSL "${CF_V6_URL}" -o "${V6_FILE}"
[[ -s "${V6_FILE}" ]] || die "IPv6 list download failed or empty"

###############################################################################
# Ensure nftables sets exist
###############################################################################

if ! nft list set inet filter cf4 >/dev/null 2>&1; then
  die "nftables set inet filter cf4 does not exist"
fi

if ! nft list set inet filter cf6 >/dev/null 2>&1; then
  die "nftables set inet filter cf6 does not exist"
fi

###############################################################################
# Repopulate nftables sets (authoritative rebuild)
###############################################################################

log "Rebuilding nftables set: cf4"
nft flush set inet filter cf4
while read -r cidr; do
  [[ -n "${cidr}" ]] && nft add element inet filter cf4 { "${cidr}" }
done < "${V4_FILE}"

log "Rebuilding nftables set: cf6"
nft flush set inet filter cf6
while read -r cidr; do
  [[ -n "${cidr}" ]] && nft add element inet filter cf6 { "${cidr}" }
done < "${V6_FILE}"

###############################################################################
# Validate nftables sets are NOT empty
###############################################################################

CF4_COUNT=$(nft list set inet filter cf4 | grep -c '/')
CF6_COUNT=$(nft list set inet filter cf6 | grep -c '/')

if [[ "${CF4_COUNT}" -eq 0 && "${CF6_COUNT}" -eq 0 ]]; then
  die "Both Cloudflare nftables sets are empty after rebuild"
fi

log "nftables OK: cf4=${CF4_COUNT} cf6=${CF6_COUNT}"

###############################################################################
# Generate nginx real_ip config
###############################################################################

log "Generating nginx real_ip config"

tmp="$(mktemp)"

{
  echo "# Auto-generated by cloudflare-update.sh"
  echo "# DO NOT EDIT MANUALLY"
  echo
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
  echo
  sed 's/^/set_real_ip_from /; s/$/;/' "${V4_FILE}"
  sed 's/^/set_real_ip_from /; s/$/;/' "${V6_FILE}"
} > "${tmp}"

install -o root -g root -m 0644 "${tmp}" "${REALIP_CONF}"
rm -f "${tmp}"

###############################################################################
# Reload nginx safely
###############################################################################

if systemctl is-active --quiet nginx; then
  log "Reloading nginx"
  nginx -t && systemctl reload nginx
else
  log "nginx not running — skipping reload"
fi

log "Cloudflare update completed successfully"
