#!/usr/bin/env bash
set -Eeuo pipefail

###############################################################################
# Cloudflare IP updater for nftables
# - Fetches IPv4 + IPv6 ranges
# - Populates nftables sets cf4 / cf6
# - Regenerates nginx real_ip config
# - FAILS HARD if sets end up empty
###############################################################################

LOCK_FILE="/var/lock/cloudflare-update.lock"
exec 9>"${LOCK_FILE}"
flock -n 9 || exit 0

###############################################################################
# Config
###############################################################################

ENV_FILE="/etc/server.env"

CF_STATE="/var/lib/server-template/cloudflare"
V4_FILE="${CF_STATE}/ips-v4.txt"
V6_FILE="${CF_STATE}/ips-v6.txt"

REALIP_CONF="/etc/nginx/conf.d/cloudflare-realip.conf"

CF_V4_URL="https://www.cloudflare.com/ips-v4"
CF_V6_URL="https://www.cloudflare.com/ips-v6"

###############################################################################
# Helpers
###############################################################################

log() {
  echo "[cloudflare-update] $*"
}

die() {
  echo "[cloudflare-update] FATAL: $*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Required command missing: $1"
}

###############################################################################
# Preconditions
###############################################################################

require_cmd curl
require_cmd nft
require_cmd awk
require_cmd grep

if [[ -f "${ENV_FILE}" ]]; then
  # shellcheck disable=SC1091
  source "${ENV_FILE}"
fi

mkdir -p "${CF_STATE}"
chmod 0700 "${CF_STATE}"

###############################################################################
# Fetch Cloudflare IP lists
###############################################################################

log "Fetching Cloudflare IPv4 ranges"
curl -fsSL "${CF_V4_URL}" > "${V4_FILE}"
[[ -s "${V4_FILE}" ]] || die "IPv4 list is empty"

log "Fetching Cloudflare IPv6 ranges"
curl -fsSL "${CF_V6_URL}" > "${V6_FILE}"
[[ -s "${V6_FILE}" ]] || die "IPv6 list is empty"

###############################################################################
# Ensure nftables sets exist
###############################################################################

nft list set inet filter cf4 >/dev/null 2>&1 || die "nft set inet filter cf4 does not exist"
nft list set inet filter cf6 >/dev/null 2>&1 || die "nft set inet filter cf6 does not exist"

###############################################################################
# Populate nftables sets (ALWAYS)
###############################################################################

log "Populating nftables IPv4 set (cf4)"
nft flush set inet filter cf4
while read -r cidr; do
  [[ -n "${cidr}" ]] && nft add element inet filter cf4 { "${cidr}" }
done < "${V4_FILE}"

log "Populating nftables IPv6 set (cf6)"
nft flush set inet filter cf6
while read -r cidr; do
  [[ -n "${cidr}" ]] && nft add element inet filter cf6 { "${cidr}" }
done < "${V6_FILE}"

###############################################################################
# Validate sets are NOT empty (CRITICAL)
###############################################################################

CF4_COUNT=$(nft list set inet filter cf4 | grep -c '/')
CF6_COUNT=$(nft list set inet filter cf6 | grep -c '/')

if [[ "${CF4_COUNT}" -eq 0 && "${CF6_COUNT}" -eq 0 ]]; then
  die "Both Cloudflare IP sets are empty — refusing to continue"
fi

log "nftables populated: cf4=${CF4_COUNT} cf6=${CF6_COUNT}"

###############################################################################
# Generate nginx real_ip config
###############################################################################

log "Generating nginx real_ip config"

{
  echo "# Auto-generated by cloudflare-update.sh"
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
  while read -r cidr; do
    echo "set_real_ip_from ${cidr};"
  done < "${V4_FILE}"
  while read -r cidr; do
    echo "set_real_ip_from ${cidr};"
  done < "${V6_FILE}"
} > "${REALIP_CONF}.tmp"

mv "${REALIP_CONF}.tmp" "${REALIP_CONF}"
chmod 0644 "${REALIP_CONF}"
chown root:root "${REALIP_CONF}"

###############################################################################
# Reload nginx safely
###############################################################################

if systemctl is-active --quiet nginx; then
  log "Reloading nginx"
  nginx -t && systemctl reload nginx
else
  log "nginx not running; skipping reload"
fi

log "Cloudflare update completed successfully"
